from .add_note import add_note_bp
from .index import index_bp
from .auth.google_auth import auth_bp
from .auth.login import login_bp
from .auth.registration import register_bp
from .auth.logout import logout_bp
from .edit_note import edit_note_bp
from .delete_note import delete_note_bp
from .note_detail import note_detail_bp
from .about import about_bp
from .profile import profile_bp
from .request_reset_form import request_reset_form_bp
from .reset_password_form import reset_password_form_bp
